// Stage-specific configuration for detail views

import type { StageTimelineStepInput } from "@/lib/timeline";

/**
 * A step in a stage's Progress panel. `requires` declares what would make the
 * step true; `deriveStageTimeline` (lib/timeline.ts) evaluates it against real
 * document and case state. Steps used to be marked complete by counting
 * document rows, which showed unpaid, ungenerated placeholders as finished.
 */
export type StageTimelineStep = StageTimelineStepInput;

export interface StageUploadSlot {
  id: string;
  name: string;
  desc: string;
  required: boolean;
  critical: boolean;
}

export interface StageDocConfig {
  id: string;
  name: string;
  matchName: string; // partial name match against documents table
  locked: boolean;
  lockedMessage: string;
}

export interface StageConfig {
  timeline: StageTimelineStep[];
  uploads: StageUploadSlot[];
  docs: StageDocConfig[];
  nextInfo: string | null;
  wgFeatures: string[];
}

export const STAGE_CONFIG: Record<number, StageConfig> = {
  1: {
    timeline: [
      { text: "Intake completed", requires: { kind: "intake" } },
      {
        text: "Request letter generated by AI",
        requires: { kind: "generated", match: "Request for Increase" },
      },
      {
        text: "LOMN template generated",
        requires: { kind: "generated", match: "LOMN Request Template" },
      },
      {
        text: "Review & finalize request letter",
        requires: { kind: "reviewed", match: "Request for Increase" },
      },
      {
        text: "Upload signed LOMN from doctor",
        requires: { kind: "uploaded", match: ["lomn", "medical necessity"] },
      },
      {
        text: "Submit request package to MLTC",
        requires: { kind: "submitted" },
      },
      {
        text: "Await MLTC determination (2–4 weeks)",
        requires: { kind: "determined" },
      },
    ],
    uploads: [
      {
        id: "u1",
        name: "Letter of Medical Necessity (LOMN)",
        desc: "Signed letter from your doctor supporting the request",
        required: true,
        critical: true,
      },
      {
        id: "u2",
        name: "Recent Medical Records",
        desc: "Hospital visits, test results, or doctor's notes",
        required: false,
        critical: false,
      },
      {
        id: "u3",
        name: "Other Supporting Documents",
        desc: "Any additional documents",
        required: false,
        critical: false,
      },
    ],
    docs: [
      {
        id: "sg1_ripc",
        name: "Request for Increase in Plan of Care",
        matchName: "Request for Increase",
        locked: false,
        lockedMessage: "",
      },
      {
        id: "sg1_lomn",
        name: "LOMN Request Template (for your Doctor)",
        matchName: "LOMN",
        locked: false,
        lockedMessage: "",
      },
    ],
    nextInfo:
      "If the MLTC denies or partially denies your request, they will issue an Initial Adverse Determination (IAD). You can then proceed to Stage 2: Internal Appeal.",
    wgFeatures: [
      "We submit the request package to your MLTC",
      "Direct communication with your case manager",
      "Follow-up calls and deadline tracking",
      "Dedicated advocate assigned to your case",
    ],
  },
  2: {
    timeline: [
      {
        text: "Upload IAD from MLTC",
        requires: { kind: "uploaded", match: ["iad", "adverse determination"] },
      },
      {
        text: "AI analyzes IAD and generates appeal",
        requires: { kind: "generated", match: "Internal Appeal" },
      },
      {
        text: "Review & finalize appeal letter",
        requires: { kind: "reviewed", match: "Internal Appeal" },
      },
      {
        text: "Submit Internal Appeal to MLTC",
        requires: { kind: "submitted" },
      },
      {
        text: "Await appeal decision (30–60 days)",
        requires: { kind: "determined" },
      },
    ],
    uploads: [
      {
        id: "u4",
        name: "Initial Adverse Determination (IAD)",
        desc: "The denial letter from your MLTC — required to generate your appeal",
        required: true,
        critical: true,
      },
      {
        id: "u5",
        name: "Updated LOMN (if available)",
        desc: "A more recent letter from your doctor",
        required: false,
        critical: false,
      },
      {
        id: "u6",
        name: "Additional Medical Evidence",
        desc: "New test results, hospital records, or specialist reports",
        required: false,
        critical: false,
      },
    ],
    docs: [
      {
        id: "sg2_appeal",
        name: "Internal Appeal Letter",
        matchName: "Internal Appeal",
        locked: true,
        lockedMessage:
          "This letter will be generated after you upload the IAD from your MLTC. The AI will analyze their determination and craft a targeted appeal.",
      },
    ],
    nextInfo:
      "If the MLTC denies your Internal Appeal, they will issue a Final Adverse Determination (FAD). You can then proceed to Stage 3: Fair Hearing.",
    wgFeatures: [
      "We submit the Internal Appeal on your behalf",
      "Follow up with the MLTC appeals department",
      "Track deadlines and ensure timely processing",
      "Dedicated advocate manages all communications",
    ],
  },
  3: {
    timeline: [
      {
        text: "Upload FAD from MLTC",
        requires: {
          kind: "uploaded",
          match: ["fad", "final adverse determination"],
        },
      },
      // Filing with OTDA happens outside the product — generating the request
      // letter is not the same as having filed it, so there is no signal to read.
      { text: "Request Fair Hearing with NYS OTDA", requires: { kind: "manual" } },
      {
        text: "Receive MLTC evidence package (includes UAS)",
        requires: { kind: "uploaded", match: ["uas", "evidence package"] },
      },
      {
        text: "AI analyzes UAS and generates Memo of Law",
        requires: { kind: "generated", match: "Memo of Law" },
      },
      {
        text: "Review & finalize Memo of Law",
        requires: { kind: "reviewed", match: "Memo of Law" },
      },
      {
        text: "Attend Fair Hearing (2–3 months)",
        requires: { kind: "submitted" },
      },
      { text: "Receive judge's decision", requires: { kind: "determined" } },
    ],
    uploads: [
      {
        id: "u7",
        name: "Final Adverse Determination (FAD)",
        desc: "The final denial from your MLTC",
        required: true,
        critical: true,
      },
      {
        id: "u8",
        name: "UAS Report / MLTC Evidence Package",
        desc: "The evidence package including the UAS assessment",
        required: true,
        critical: true,
      },
      {
        id: "u9",
        name: "Updated LOMN",
        desc: "Most recent letter from your doctor",
        required: false,
        critical: false,
      },
      {
        id: "u10",
        name: "Other Evidence",
        desc: "Photos, personal statements, caregiver logs",
        required: false,
        critical: false,
      },
    ],
    docs: [
      {
        id: "sg3_hearing",
        name: "Fair Hearing Request",
        matchName: "Fair Hearing",
        locked: true,
        lockedMessage:
          "This request will be generated after you upload the FAD.",
      },
      {
        id: "sg3_memo",
        name: "Memo of Law",
        matchName: "Memo of Law",
        locked: true,
        lockedMessage:
          "This legal memorandum will be generated after we receive and analyze the MLTC's evidence package, including the UAS report.",
      },
    ],
    nextInfo: null,
    wgFeatures: [
      "We file the Fair Hearing request with NYS OTDA",
      "Full analysis of UAS report and evidence package",
      "Hearing preparation and evidence organization",
      "Dedicated advocate attends the hearing with you",
    ],
  },
};
