import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  deriveStageTimeline,
  type StageTimelineEntry,
} from "@/lib/timeline";
import { STAGE_CONFIG } from "@/lib/stage-config";
import type { Document, DocumentStatus, GenerationStatus } from "@/types";
import type { StagePaymentGate } from "@/lib/billing/payment-required";

const CASE_ID = "11111111-2222-3333-4444-555555555555";
const CREATED_AT = "2026-03-01T10:00:00.000Z";

function gate(stage: number): StagePaymentGate {
  return { caseId: CASE_ID, stage, amount: 9900 };
}

function doc(overrides: Partial<Document> & { name: string }): Document {
  return {
    id: `doc-${overrides.name}`,
    case_id: CASE_ID,
    type: "generated",
    stage: 1,
    status: "pending",
    format: "letter",
    storage_path: null,
    ocr_text: null,
    content: null,
    version: 1,
    generation_status: null,
    generation_error: null,
    ocr_status: null,
    ocr_error: null,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
    ...overrides,
  };
}

function generated(
  name: string,
  generation_status: GenerationStatus,
  status: DocumentStatus = "review_needed"
): Document {
  return doc({
    name,
    generation_status,
    status: generation_status === "ready" ? status : "pending",
    content: generation_status === "ready" ? "Dear Care Manager," : null,
  });
}

function uploaded(name: string, stage = 1): Document {
  return doc({
    name,
    stage: stage as Document["stage"],
    type: "uploaded",
    status: "uploaded",
    format: "pdf",
    storage_path: "case/file.pdf",
    ocr_status: "pending",
  });
}

/** The exact Stage 1 placeholders intake writes. */
const STAGE1_PLACEHOLDERS = [
  generated("Request for Increase in Plan of Care", "pending"),
  generated("LOMN Request Template (for your Doctor)", "pending"),
];

function stage1(
  documents: Document[],
  extra: Partial<Parameters<typeof deriveStageTimeline>[0]> = {}
): StageTimelineEntry[] {
  return deriveStageTimeline({
    steps: STAGE_CONFIG[1].timeline,
    documents,
    stageNum: 1,
    currentStage: 1,
    stageStatus: "in_progress",
    ...extra,
  });
}

function byText(
  entries: StageTimelineEntry[],
  fragment: string
): StageTimelineEntry {
  const entry = entries.find((e) => e.text.includes(fragment));
  if (!entry) {
    throw new Error(
      `No step matching "${fragment}" in: ${entries.map((e) => e.text).join(" | ")}`
    );
  }
  return entry;
}

describe("deriveStageTimeline — unpaid stage", () => {
  it("does NOT mark generated steps complete when the stage fee is unpaid", () => {
    // The row-counting heuristic marked the first N steps done, so an unpaid
    // Stage 1 with two pending placeholders showed "Request letter generated by
    // AI" and "LOMN template generated" as complete.
    const entries = stage1(STAGE1_PLACEHOLDERS, { paymentGate: gate(1) });

    expect(byText(entries, "Request letter generated by AI")).toMatchObject({
      state: "blocked",
    });
    expect(byText(entries, "LOMN template generated")).toMatchObject({
      state: "blocked",
    });
    expect(byText(entries, "Review & finalize request letter")).toMatchObject({
      state: "blocked",
    });

    // Only intake is genuinely complete.
    const done = entries.filter((e) => e.state === "done");
    expect(done.map((e) => e.text)).toEqual(["Intake completed"]);
  });

  it("does not let an unrelated upload push the generated steps to done", () => {
    // Row counting summed generated + uploaded rows, so uploading the LOMN
    // advanced the *earlier* generation steps regardless of their state.
    const entries = stage1(
      [...STAGE1_PLACEHOLDERS, uploaded("LOMN from Dr. Smith")],
      { paymentGate: gate(1) }
    );

    expect(byText(entries, "Request letter generated by AI").state).toBe(
      "blocked"
    );
    expect(byText(entries, "Upload signed LOMN from doctor").state).toBe("done");
  });

  it("ignores a gate belonging to a different stage", () => {
    const entries = stage1(
      [
        generated("Request for Increase in Plan of Care", "ready"),
        generated("LOMN Request Template (for your Doctor)", "ready"),
      ],
      { paymentGate: gate(2) }
    );

    expect(byText(entries, "Request letter generated by AI").state).toBe("done");
  });
});

describe("deriveStageTimeline — document states", () => {
  it("marks a generated step done only when the document is ready", () => {
    const entries = stage1([
      generated("Request for Increase in Plan of Care", "ready"),
      generated("LOMN Request Template (for your Doctor)", "ready"),
    ]);

    expect(byText(entries, "Request letter generated by AI").state).toBe("done");
    expect(byText(entries, "LOMN template generated").state).toBe("done");
    // Ready but not yet reviewed by the client.
    expect(byText(entries, "Review & finalize request letter")).toMatchObject({
      state: "upcoming",
      current: true,
    });
  });

  it("surfaces a failed generation as failed", () => {
    const entries = stage1([
      generated("Request for Increase in Plan of Care", "failed"),
      generated("LOMN Request Template (for your Doctor)", "ready"),
    ]);

    expect(byText(entries, "Request letter generated by AI").state).toBe(
      "failed"
    );
  });

  it("surfaces an in-flight generation as in progress", () => {
    const entries = stage1([
      generated("Request for Increase in Plan of Care", "generating"),
      generated("LOMN Request Template (for your Doctor)", "generating"),
    ]);

    expect(byText(entries, "Request letter generated by AI").state).toBe(
      "in_progress"
    );
    // A step with its own signal doesn't also get the CURRENT badge.
    expect(entries.every((e) => !e.current)).toBe(true);
  });

  it("shows pending-but-paid as upcoming rather than blocked", () => {
    const entries = stage1(STAGE1_PLACEHOLDERS, { paymentGate: null });

    expect(byText(entries, "Request letter generated by AI")).toMatchObject({
      state: "upcoming",
      current: true,
    });
  });

  it("completes the review step only once the client marks it reviewed", () => {
    const entries = stage1([
      generated("Request for Increase in Plan of Care", "ready", "reviewed"),
      generated("LOMN Request Template (for your Doctor)", "ready"),
    ]);

    expect(byText(entries, "Review & finalize request letter").state).toBe(
      "done"
    );
  });
});

describe("deriveStageTimeline — case-level steps", () => {
  it("keeps submission and determination upcoming on an in-progress stage", () => {
    const entries = stage1(STAGE1_PLACEHOLDERS, { paymentGate: gate(1) });

    expect(byText(entries, "Submit request package").state).toBe("upcoming");
    expect(byText(entries, "Await MLTC determination").state).toBe("upcoming");
  });

  it("marks submission done and the wait in progress once submitted", () => {
    const entries = stage1(
      [
        generated("Request for Increase in Plan of Care", "ready", "reviewed"),
        generated("LOMN Request Template (for your Doctor)", "ready"),
        uploaded("Signed LOMN"),
      ],
      { stageStatus: "submitted" }
    );

    expect(byText(entries, "Submit request package").state).toBe("done");
    expect(byText(entries, "Await MLTC determination").state).toBe(
      "in_progress"
    );
  });

  it("marks every step done for a stage the case has moved past", () => {
    const entries = deriveStageTimeline({
      steps: STAGE_CONFIG[1].timeline,
      documents: STAGE1_PLACEHOLDERS,
      stageNum: 1,
      currentStage: 2,
      stageStatus: "in_progress",
    });

    expect(entries.every((e) => e.state === "done")).toBe(true);
  });

  it("marks nothing done for a stage the case has not reached", () => {
    const entries = deriveStageTimeline({
      steps: STAGE_CONFIG[3].timeline,
      documents: [],
      stageNum: 3,
      currentStage: 1,
      stageStatus: "in_progress",
    });

    expect(entries.every((e) => e.state === "upcoming" && !e.current)).toBe(
      true
    );
  });
});

describe("deriveStageTimeline — stages 2 and 3", () => {
  it("does not mark the Stage 2 appeal generated while its fee is unpaid", () => {
    const entries = deriveStageTimeline({
      steps: STAGE_CONFIG[2].timeline,
      documents: [
        uploaded("Initial Adverse Determination (IAD)", 2),
        { ...generated("Internal Appeal Letter", "pending"), stage: 2 },
      ],
      stageNum: 2,
      currentStage: 2,
      stageStatus: "in_progress",
      paymentGate: gate(2),
    });

    expect(byText(entries, "Upload IAD from MLTC").state).toBe("done");
    expect(byText(entries, "generates appeal")).toMatchObject({
      state: "blocked",
    });
    expect(byText(entries, "Review & finalize appeal letter").state).toBe(
      "blocked"
    );
    expect(entries.filter((e) => e.state === "done")).toHaveLength(1);
  });

  it("never marks a manual Stage 3 step done off the back of documents", () => {
    const entries = deriveStageTimeline({
      steps: STAGE_CONFIG[3].timeline,
      documents: [
        uploaded("Final Adverse Determination (FAD)", 3),
        uploaded("UAS Report", 3),
        { ...generated("Memo of Law", "ready"), stage: 3 },
        { ...generated("Fair Hearing Request", "ready"), stage: 3 },
      ],
      stageNum: 3,
      currentStage: 3,
      stageStatus: "in_progress",
    });

    // Generating the Fair Hearing Request is not the same as filing it.
    expect(byText(entries, "Request Fair Hearing with NYS OTDA").state).toBe(
      "upcoming"
    );
    expect(byText(entries, "Upload FAD from MLTC").state).toBe("done");
    expect(byText(entries, "Receive MLTC evidence package").state).toBe("done");
    expect(byText(entries, "generates Memo of Law").state).toBe("done");
    expect(byText(entries, "Attend Fair Hearing").state).toBe("upcoming");
  });
});

describe("STAGE_CONFIG", () => {
  it("declares a requirement for every step of every stage", () => {
    for (const [stage, config] of Object.entries(STAGE_CONFIG)) {
      for (const step of config.timeline) {
        expect(
          step.requires,
          `Stage ${stage} step "${step.text}" has no requires — it would silently never complete`
        ).toBeDefined();
      }
    }
  });

  it("points every generated/reviewed step at a real document name", () => {
    // A typo here doesn't fail the build — it makes a step permanently blocked.
    // NAME_MAP is read from source rather than imported because
    // lib/document-generation.ts constructs an OpenAI client at module scope
    // (same reason as tests/doc-name-map-consistency.test.ts).
    const source = readFileSync(
      join(__dirname, "document-generation.ts"),
      "utf8"
    );
    const nameMap = source.split("NAME_MAP")[1].split("};")[0];
    const realNames = [...nameMap.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    expect(realNames).toHaveLength(5);

    for (const config of Object.values(STAGE_CONFIG)) {
      for (const step of config.timeline) {
        const req = step.requires;
        if (req?.kind !== "generated" && req?.kind !== "reviewed") continue;
        expect(
          realNames.some((n) => n.includes(req.match)),
          `Step "${step.text}" matches on "${req.match}", which no document is named`
        ).toBe(true);
      }
    }
  });
});
